// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path=".snaplet/snaplet.d.ts" />
// This config was generated by Snaplet make sure to check it over before using it.
import { copycat, faker } from "@snaplet/copycat";
import { defineConfig } from "snaplet";
copycat.setHashKey("bREFjOONG553rFk9");
export default defineConfig({
  transform: {
    $mode: "unsafe",
    public: {
      admin({ row }) {
        return {
          id: copycat.int(row.id, {
            min: 1,
            max: 65535,
          }),
        };
      },
      affirmation_reminder({ row }) {
        return {
          name: copycat.fullName(row.name),
        };
      },
      blacklistToken({ row }) {
        return {
          token: copycat.uuid(row.token),
        };
      },
      calendar({ row }) {
        return {
          timeZone: copycat.timezone(row.timeZone).slice(0, 40),
        };
      },
      cbtCourse({ row }) {
        return {
          name: copycat.fullName(row.name, {
            limit: 80,
          }),
        };
      },
      cbtModule({ row }) {
        return {
          name: copycat.fullName(row.name, {
            limit: 100,
          }),
        };
      },
      cbtTopic({ row }) {
        return {
          name: copycat.fullName(row.name, {
            limit: 100,
          }),
        };
      },
      chatEvent({ row }) {
        return {
          timeZone: copycat.timezone(row.timeZone).slice(0, 40),
          startTime: copycat.dateString(row.startTime, {
            minYear: 2020,
          }),
          endTime: copycat.dateString(row.endTime, {
            minYear: 2020,
          }),
          mobile: copycat.fullName(row.mobile, {
            limit: 13,
          }),
        };
      },
      client({ row }) {
        return {
          label: copycat.fullName(row.label, {
            limit: 120,
          }),
          industry: copycat.country(row.industry).slice(0, 120),
          KRAPin: copycat.username(row.KRAPin, {
            limit: 200,
          }),
        };
      },
      discountCode({ row }) {
        return {
          channel: copycat.phoneNumber(row.channel).slice(0, 20),
        };
      },
      goal_category({ row }) {
        return {
          title: copycat.fullName(row.title, {
            limit: 255,
          }),
        };
      },
      groupEvent({ row }) {
        return {
          timeZone: copycat.timezone(row.timeZone).slice(0, 40),
        };
      },
      groupSession({ row }) {
        return {
          startTime: copycat.dateString(row.startTime, {
            minYear: 2020,
          }),
          endTime: copycat.dateString(row.endTime, {
            minYear: 2020,
          }),
        };
      },
      groupTopic({ row }) {
        return {
          name: copycat.fullName(row.name, {
            limit: 80,
          }),
        };
      },
      human({ row }) {
        return {
          role: copycat.fullName(row.role, {
            limit: 50,
          }),
          name: copycat.fullName(row.name, {
            limit: 80,
          }),
          email: copycat.email(row.email, {
            limit: 400,
          }),
          mobile: copycat.fullName(row.mobile, {
            limit: 120,
          }),
          lastLogin: copycat.dateString(row.lastLogin, {
            minYear: 2020,
          }),
        };
      },
      journal({ row }) {
        return {
          tag: copycat.timezone(row.tag),
        };
      },
      message({ row }) {
        return {
          chatId: copycat.int(row.chatId, {
            min: 1,
            max: 65535,
          }),
          role: copycat.fullName(row.role, {
            limit: 20,
          }),
        };
      },
      onsiteEvent({ row }) {
        return {
          startTime: copycat.dateString(row.startTime, {
            minYear: 2020,
          }),
          endTime: copycat.dateString(row.endTime, {
            minYear: 2020,
          }),
        };
      },
      order({ row }) {
        return {
          currency: copycat.scramble(row.currency),
        };
      },
      phoneEvent({ row }) {
        return {
          timeZone: copycat.timezone(row.timeZone).slice(0, 40),
          startTime: copycat.dateString(row.startTime, {
            minYear: 2020,
          }),
          endTime: copycat.dateString(row.endTime, {
            minYear: 2020,
          }),
          mobile: copycat.fullName(row.mobile, {
            limit: 13,
          }),
        };
      },
      quickReplies({ row }) {
        return {
          value: copycat.int(row.value, {
            min: 0,
            max: 65535,
          }),
        };
      },
      referral_codes({ row }) {
        return {
          email: copycat.email(row.email, {
            limit: 100,
          }),
          name: copycat.fullName(row.name, {
            limit: 100,
          }),
        };
      },
      shamiriScore({ row }) {
        return {
          domain: copycat.email(row.domain, {
            limit: 20,
          }),
          score: copycat.int(row.score, {
            min: 0,
            max: 65535,
          }),
        };
      },
      therapist({ row }) {
        return {
          dateOfBirth: copycat
            .dateString(row.dateOfBirth, {
              minYear: 1950,
              maxYear: 2000,
            })
            .slice(0, 10),
          gmail: copycat.email(row.gmail, {
            limit: 200,
          }),
          timeZone: copycat.timezone(row.timeZone).slice(0, 80),
        };
      },
      upload_all_social_media_content_20240417164637({ row }) {
        return {
          shares: copycat.int(row.shares, {
            min: 0,
            max: 16777215,
          }),
          saves: copycat.int(row.saves, {
            min: 0,
            max: 16777215,
          }),
        };
      },
      upload_all_social_media_content___instagram_20240417165124({ row }) {
        return {
          shares: copycat.int(row.shares, {
            min: 0,
            max: 16777215,
          }),
        };
      },
      upload_all_social_media_content___instagram_20240418081917({ row }) {
        return {
          shares: copycat.int(row.shares, {
            min: 0,
            max: 16777215,
          }),
        };
      },
      upload_all_social_media_content___instagram_20240418083235({ row }) {
        return {
          shares: copycat.int(row.shares, {
            min: 0,
            max: 16777215,
          }),
        };
      },
      upload_all_social_media_content___tiktok_20240417165129({ row }) {
        return {
          shares: copycat.int(row.shares, {
            min: 0,
            max: 16777215,
          }),
          saves: copycat.int(row.saves, {
            min: 0,
            max: 16777215,
          }),
        };
      },
      upload_all_social_media_content___tiktok_20240418081906({ row }) {
        return {
          shares: copycat.int(row.shares, {
            min: 0,
            max: 16777215,
          }),
          saves: copycat.int(row.saves, {
            min: 0,
            max: 16777215,
          }),
        };
      },
      upload_all_social_media_content___tiktok_20240418082958({ row }) {
        return {
          shares: copycat.int(row.shares, {
            min: 0,
            max: 16777215,
          }),
          saves: copycat.int(row.saves, {
            min: 0,
            max: 16777215,
          }),
        };
      },
      upload_instagram_stats_20240305063948({ row }) {
        return {
          shares: copycat.int(row.shares, {
            min: 0,
            max: 16777215,
          }),
        };
      },
      upload_jan_23_2024_feb_19_2024_2568919529982082_20240223100838({ row }) {
        return {
          shares: copycat.int(row.shares, {
            min: 0,
            max: 16777215,
          }),
        };
      },
      upload_linkedin_posts_20240305072212({ row }) {
        return {
          audience: copycat.scramble(row.audience),
        };
      },
      upload_shamiri_health_ltd_revenue_2023__1__20240318123242({ row }) {
        return {
          total: copycat.fullName(row.total, {
            limit: 255,
          }),
        };
      },
      upload_social_media_metrics___tiktok_20240305073415({ row }) {
        return {
          duration: copycat.scramble(row.duration),
          caption: copycat.scramble(row.caption),
          shares: copycat.int(row.shares, {
            min: 0,
            max: 16777215,
          }),
          saves: copycat.int(row.saves, {
            min: 0,
            max: 16777215,
          }),
        };
      },
      user({ row }) {
        return {
          dateOfBirth: copycat
            .dateString(row.dateOfBirth, {
              minYear: 1950,
              maxYear: 2000,
            })
            .slice(0, 10),
          timeZone: copycat.timezone(row.timeZone),
          gender2: copycat.scramble(row.gender2),
          pinH: copycat.hex(row.pinH),
        };
      },
      userDisplay({ row }) {
        return {
          streamId: copycat.streetAddress(row.streamId).slice(0, 50),
        };
      },
      userRecord({ row }) {
        return {
          flow: copycat
            .dateString(row.flow, {
              maxYear: 1999,
            })
            .slice(0, 60),
          stateId: copycat.state(row.stateId),
        };
      },
    },
  },
});
